name: Testing 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      env:
        TESTME: ${{ secrets.MY_SECRET}}
      run: |
        .github/workflows/testing.sh "$TESTME" 

